#admin.dashboard:
#  path: /
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
#  defaults:
#    template: Admin/Pages/description.html.twig

admin.sliders:
  path: /sliders
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/sliders.html.twig

admin.login:
  path: /login
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/login.html.twig

admin.logout:
  path: /logout

admin.descriptions:
  path: /description
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/descriptions.html.twig

admin.catalog_page:
  path: /catalog
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/catalog.html.twig

admin.video_page:
  path: /video
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: Admin/Pages/video.html.twig
