#index:
#    path: /
#    controller: App\Controller\DefaultController::index
bazinga_jstranslation_js:
  path:  /translations/{domain}.{_format}
  defaults: { _controller: bazinga.jstranslation.controller:getTranslationsAction, domain: null, _format: "js" }
  methods:  [ GET ]
  options:
    i18n: false
    expose: true
  requirements:
    _format: js|json
    domain: "[\\w]+"

admin:
  resource: 'routes/routes_admin.yaml'
  prefix: /admin
  options:
    expose: true
